# Generated by Django 4.1 on 2023-05-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeDeGoiaba',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField(default=0)),
            ],
        ),
    ]
